server:
  port: 8080
  #  address: 172.26.11.126
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: 
    driver-class-name: 
    hikari:
      username: ssafy
      password: ssafy_juyuso!@
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        show-sql: true
  devtools:
    livereload:
      enabled: true
jwt:
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
  expiration: 1296000000 # unit is ms. 15 * 24 * 60 * 60 * 1000 = 15days

social:
  kakao:
    client-id: 
    redirect: 
    url:
      login: https://kauth.kakao.com/oauth/authorize
      token: https://kauth.kakao.com/oauth/token
      profile: https://kapi.kakao.com/v2/user/me
      unlink: https://kapi.kakao.com/v1/user/unlink

logging:
  file:
    name: ./web.log
  level:
    root: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      #        SQL: DEBUG
      springframework:
        web: DEBUG
        boot: DEBUG
        security: DEBUG
      apache:
        tiles: INFO

app:
  fileUpload:
    path: /upload

openvidu:
  url: https://i6e101.p.ssafy.io:4443/
  secret: SSAFY